<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleAdminController::new' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.T1FLlUF', 'get_ServiceLocator_T1FLlUFService.php', true],
    'App\\Controller\\ArticleController::toggleArticleHeart' => ['privates', '.service_locator.1n6P8pO', 'get_ServiceLocator_1n6P8pOService.php', true],
    'App\\Controller\\ArticleAdminController:new' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.T1FLlUF', 'get_ServiceLocator_T1FLlUFService.php', true],
    'App\\Controller\\ArticleController:toggleArticleHeart' => ['privates', '.service_locator.1n6P8pO', 'get_ServiceLocator_1n6P8pOService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
