<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\MarkdownHelper' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/MarkdownHelper.php';

$a = new \Monolog\Handler\StreamHandler(($this->targetDirs[2].'/log/markdown.log'), 100, true, NULL);
$a->pushProcessor(($this->privates['monolog.processor.psr_log_message'] ?? $this->privates['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor()));

$b = new \Symfony\Bridge\Monolog\Logger('markdown');
$b->pushProcessor(($this->privates['debug.log_processor'] ?? $this->privates['debug.log_processor'] = new \Symfony\Bridge\Monolog\Processor\DebugProcessor()));
$b->pushHandler(($this->privates['monolog.handler.console'] ?? $this->privates['monolog.handler.console'] = new \Symfony\Bridge\Monolog\Handler\ConsoleHandler(NULL, true, array())));
$b->pushHandler($a);
$b->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));

return $this->privates['App\Service\MarkdownHelper'] = new \App\Service\MarkdownHelper(($this->services['cache.app'] ?? $this->getCache_AppService()), ($this->services['markdown.parser'] ?? $this->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Light()), $b, true);
