<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ASISTmE' shared service.

return $this->privates['service_locator.ASISTmE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('markdownHelper' => function (): ?\App\Services\MarkdownHelper {
    return ($this->privates['App\Service\MarkdownHelper'] ?? $this->load('getMarkdownHelperService.php'));
}, 'slack' => function (): ?\App\Services\SlackClient {
    return ($this->privates['App\Service\SlackClient'] ?? $this->load('getSlackClientService.php'));
}));
