<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FwJXtGu' shared service.

return $this->privates['.service_locator.FwJXtGu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.FwJXtGu.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.FwJXtGu": it references class "App\\Entity\\Article" but no such service exists.'],
    'slack' => ['privates', 'App\\Service\\SlackClient', 'getSlackClientService.php', true],
]);
