<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.b0umcGQ' shared service.

return $this->privates['.service_locator.b0umcGQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'markdownHelper' => ['privates', 'App\\Service\\MarkdownHelper', 'getMarkdownHelperService.php', true],
    'slack' => ['privates', 'App\\Service\\SlackClient', 'getSlackClientService.php', true],
]);
