<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nexy_slack.client' shared service.

include_once $this->targetDirs[3].'/vendor/php-http/httplug-bundle/ClientFactory/ClientFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/httplug-bundle/ClientFactory/AutoDiscoveryFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/httplug-bundle/Collector/ProfileClientFactory.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/Plugin.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/Plugin/ContentLengthPlugin.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/Plugin/RedirectPlugin.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/PluginClient.php';
include_once $this->targetDirs[3].'/vendor/php-http/discovery/src/MessageFactoryDiscovery.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/HttpMethodsClient.php';
include_once $this->targetDirs[3].'/vendor/nexylan/slack/src/Client.php';

return $this->services['nexy_slack.client'] = new \Nexy\Slack\Client($this->getEnv('string:SLACK_WEBHOOK_ENDPOINT'), $this->parameters['nexy_slack.config'], new \Http\Client\Common\HttpMethodsClient(($this->privates['Http\Client\Common\PluginClientFactory'] ?? $this->getPluginClientFactoryService())->createClient((new \Http\HttplugBundle\Collector\ProfileClientFactory(new \Http\HttplugBundle\ClientFactory\AutoDiscoveryFactory(), ($this->privates['httplug.collector.collector'] ?? $this->privates['httplug.collector.collector'] = new \Http\HttplugBundle\Collector\Collector()), ($this->privates['httplug.collector.formatter'] ?? $this->getHttplug_Collector_FormatterService()), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))))->createClient(array()), array(0 => new \Http\Client\Common\Plugin\ContentLengthPlugin(), 1 => new \Http\Client\Common\Plugin\RedirectPlugin(array('preserve_header' => true, 'use_default_for_multiple' => true))), array('client_name' => 'app')), \Http\Discovery\MessageFactoryDiscovery::find()));
