<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVYuP45\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVYuP45/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVYuP45.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVYuP45\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRVYuP45\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RVYuP45',
    'container.build_id' => 'a351dd8c',
    'container.build_time' => 1552469221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVYuP45');
