<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3a8V9wV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3a8V9wV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3a8V9wV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3a8V9wV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3a8V9wV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3a8V9wV',
    'container.build_id' => '6e79ee4d',
    'container.build_time' => 1554666632,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3a8V9wV');
