<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSrO2Fnu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSrO2Fnu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSrO2Fnu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSrO2Fnu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSrO2Fnu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SrO2Fnu',
    'container.build_id' => '4b7e4406',
    'container.build_time' => 1551863366,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSrO2Fnu');
